spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8080/realms/mindtrack-journal}

security:
  public-endpoints:
    - /api/v1/auth/login
    - /api/v1/auth/register
    - /api/v1/auth/refresh-token
    - /api/v1/plans
    - /api/v1/plans/**