server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_service
    username: ${DB_USER:admin}
    password: ${DB_PASS:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:root}@${EUREKA_SERVER_HOST:localhost}:8761/eureka/

keycloak:
  realm: ${KEYCLOAK_REALM:mindtrack-journal}
  auth-server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
  client-id: user-service-client
  credentials:
    client-secret: ${KEYCLOAK_USER_CLIENT_SECRET:user-service-secret}